#[path = "1.rs"]
pub mod day_1;
#[path = "10.rs"]
pub mod day_10;
#[path = "11.rs"]
pub mod day_11;
#[path = "2.rs"]
pub mod day_2;
#[path = "3.rs"]
pub mod day_3;
#[path = "4.rs"]
pub mod day_4;
#[path = "5.rs"]
pub mod day_5;
#[path = "6.rs"]
pub mod day_6;
#[path = "7.rs"]
pub mod day_7;
#[path = "8.rs"]
pub mod day_8;
#[path = "9.rs"]
pub mod day_9;
